/**
 * Servicios Pbkc
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Marcas {
    fechaRegistro?: Date;
    foto?: string;
    id?: number;
    nombre?: string;
    numeroSerie?: string;
}
